### ISSUE TITLE
Electrum icon in taskbar differs

### ISSUE THREAD

**Issue by rmrm-rami** [Feathercoin-Foundation/electrum-ftc#16] opened 2018-04-01 09:37 UTC
Left icon (darker) is from the "portable" version, right logo (brighter) is from the "setup" version. We may want to use the same icon for all the different versions.

![image](https://user-images.githubusercontent.com/37974898/38171818-0f567a32-35a1-11e8-9dcc-255ff14884bb.png)

**Comment by toxeus** [comment] 2018-04-02 05:12
Thank you! That's a very good catch. I can confirm this. The reason is that Qt [overrides](https://github.com/Feathercoin-Foundation/electrum-ftc/blob/9bfa9c69428935e9bce7430415583b6444d7d9df/gui/qt/main_window.py#L162) the icon. This doesn't seem to affect the setup version. My assumption is that the [icon](https://github.com/Feathercoin-Foundation/electrum-ftc/blob/9bfa9c69428935e9bce7430415583b6444d7d9df/contrib/build-wine/electrum.nsi#L75) is defined in the registry which has precedence over everything else.

**Comment by toxeus** [comment] 2018-04-02 06:17
Preventing Qt from "overriding" the icon on Windows leads actually to no icon at all and it falls back to use an ugly fallback icon. Looks like we need a bright version of `electrum.png` and we decide at runtime depending on the plafrom which one to use.

**Comment by lclc** [comment] 2018-04-11 16:13
Fixed by @toxeus with https://github.com/Feathercoin-Foundation/electrum-ftc/commit/6f85c56a606629aa61f1a7acd2a98028221b4042 and https://github.com/Feathercoin-Foundation/electrum-ftc/commit/efa3837b0e7a270675752bf0f328bf86b4a0c93e

**Closed as completed by lclc** 2018-04-11 16:13 UTC
Labels: bug
